### ISSUE TITLE
Make repositories public 4

### ISSUE THREAD

**Issue by breuert** [stella-project/stella-server#14]
- [x] Revise readme of stella server
- [x] Revise readme of stella app
- [x] Revise readme of stella search
- [x] prepare and check demo setup
- [x] test on windows - won't fix

**Comment by ljgarcia** [comment]
@breuert @benjwolff @narges1212 I just finished running the scripts as detailed at https://github.com/stella-project/stella-search#demo-setup-of-the-entire-infrastructure

I think some information is missing. Please be aware that I am following the instructions there without even trying to figure out on my own what should I change to make it work.

* There is not gesis.jsonl under data/index but a gesis-datasets.jsonl file under data/datasets. I copied that one into data/index. Is that what I am suppose to do if I want to index both LIVIVO and GESIS? Am I allowed to index more than one file? Will it work in a laptop or should I go for one or the other?
* If both are index, which one will be used later for the search? Both?
* Whenever I need to run a URL related to a docker, I use an interactive or so mode. The instructions to run the docker did not include any of this sort so the docker run and finished. I get a "page is not working" whenever I try any of the links. What am I doing wrong?
* Will the examples work for both LIVIVO and GESIS? vaccine, treatment, epidemic? Who do I know if I am testing one or the other? There is only one URL mentioned http://0.0.0.0:8000

**Comment by breuert** [comment]
Hi Leyla, thank you for having a look at the demo. The provided demo is tailored for example data from LIVIVO only. Several months ago, we had a discussion about which data to choose and we decided, it would be better to use sample data from LIVIVO since our GESIS sample data consisted mostly of german texts. **Actually, it is not required to copy any of the data into another directory.** This means no recommendations of datasets will be provided in our demo, since we do not have any datasets for LIVIVO.

Apart from the mentioned flaws in the description: were there any problems that are specifically related to Windows?

**Comment by ljgarcia** [comment]
Hi Timo,

Not sure there is a problem at all in Windows. I could not test the links
because the dockers run and close so there is no way to get to the 80, 8080
links to see how things work.

If it is a matter of using the interactive mode, it should be added to the
documentation. If you think that would solve the problem, I could go ahead
and test it again and then let you know.

**Comment by ljgarcia** [comment]
@breuert this is what I am trying to run: https://github.com/stella-project/stella-search#demo-setup-of-the-entire-infrastructure
I am not even sure how it runs in linux. Any chance you can create a video on how you run in in linux/mac so I can see what you run and what the expected behavior is?
