### ISSUE TITLE
Submission mechanism: Link GitHub repositories to user accounts

### ISSUE THREAD

**Issue by breuert** [stella-project/stella-server#16]
- [x] link GitHub-URL of the the repository to the user account via the user interface
- [x] implement a stella-bot that updates the yml-file of the `stella-app` (Make separate yml-files for GESIS and LIVIVO! GESIS only needs recommender systems and vice versa LIVIVO only ranking systems)

**Comment by benjwolff** [comment]
Everything worked as expected.
Here is what I did:

- set environment variable (github access token, Automator)
- started STELLA-Server locally
- uploaded participant-run file
- See screenshot for automatically generated github-repo

![image](https://user-images.githubusercontent.com/45824909/100352907-f63ed680-2fed-11eb-8f24-526e74571ace.png)
