### ISSUE TITLE
Automated GitHub repositories from run uploads

### ISSUE THREAD

**Issue by breuert** [stella-project/stella-server#17]
- [x] Distinct between recommender and ranking systems when uploading the run files
- [x] Implement ~~run file splitting~~ (in order to commit files with less than 100MB) **&rarr; file compression**
- [x] Improve interactions between stella-automator and GitHub

**Comment by benjwolff** [comment]
Everything worked as expected.
See comments here https://github.com/stella-project/stella-app/issues/25
